CREATE DATABASE appDatabase;

USE appDatabase;

CREATE TABLE rockets (
	rocketID VARCHAR(20) PRIMARY KEY,
	rocketJSON VARCHAR(600)
);

CREATE TABLE users (
	userID INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(40) NOT NULL,
	password VARCHAR(60) NOT NULL,
	name VARCHAR(60) NOT NULL,
	PRIMARY KEY(userID)
);

CREATE TABLE selectedRockets(
	rocketID VARCHAR(20),
	userID INT,

	PRIMARY KEY(rocketID,userID),

	FOREIGN KEY(rocketID) REFERENCES 
	rockets(rocketID) ON DELETE CASCADE,

	FOREIGN KEY(userID) REFERENCES 
	users(userID) ON DELETE CASCADE
);
